# Generated by Django 5.2.4 on 2025-07-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paragrafos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragrafo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField()),
                ('resumo', models.TextField(max_length=280)),
                ('autor', models.CharField()),
                ('tempo_leitura', models.IntegerField()),
                ('data_criacao', models.DateField(auto_now=True)),
                ('capa', models.ImageField(upload_to='media/')),
                ('conteudo', models.ManyToManyField(to='noticias.paragrafos')),
            ],
        ),
    ]
